version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6.10
     steps:
       - checkout
       - run:
          name: test
          command: mocha
     branches:
      only:
        - unit_tests